version: "3"

services:
  telemetry-frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    read_only: true
    tmpfs:
      - /var/cache/nginx:uid=101,gid=101
      - /var/run:uid=101,gid=101
      - /app/tmp:uid=101,gid=101
    environment:
      SUBSTRATE_TELEMETRY_URL: wss://feed.3dpass.network/feed
    ports:
      - '127.0.0.1:8087:8000'
    restart: unless-stopped

  telemetry-backend-shard:
    build:
      dockerfile: Dockerfile
      context: ./backend/
    read_only: true
    command: [
      'telemetry_shard',
      '--listen', '0.0.0.0:9001',
      '--core', 'http://telemetry-backend-core:9000/shard_submit'
    ]
    ports:
      - '127.0.0.1:8088:9001'
    restart: unless-stopped

  telemetry-backend-core:
    build:
      dockerfile: Dockerfile
      context: ./backend/
    read_only: true
    command: [
      'telemetry_core',
      '--listen', '0.0.0.0:9000'
    ]
    ports:
      - '127.0.0.1:8089:9000'
    restart: unless-stopped
