version: "3"

services:
  telemetry-frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    # Copy in changes to the ui, so no need to rebuild the images.
    volumes:
      - /app/node_modules
      - ./packages:/app/packages
    ports:
      - 3000:80
    expose:
      - 3000
  telemetry-backend-shard:
    build:
      dockerfile: shard.Dockerfile
      context: ./backend/
    environment:
      - PORT=8001
    command: ['--core', 'http://telemetry-backend-core:8000']
    ports:
      - 8001:8001
    expose:
      - 8001
  telemetry-backend-core:
    build:
      dockerfile: telemetry.Dockerfile
      context: ./backend/
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    expose:
      - 8000
